"""Add is_ai_response field to SlackMessage

Revision ID: 3c7bbf8421f3
Revises: 92c0865fa9da
Create Date: 2025-07-28 02:40:23.107331

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3c7bbf8421f3'
down_revision = '92c0865fa9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slackmessage', sa.Column('is_ai_response', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slackmessage', 'is_ai_response')
    # ### end Alembic commands ###
