"""Update SlackMessage model

Revision ID: 92c0865fa9da
Revises: 64fe962db5e6
Create Date: 2025-07-28 01:29:18.886604

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '92c0865fa9da'
down_revision = '64fe962db5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
