"""Initial migration

Revision ID: d26d6cd4ea67
Revises: 
Create Date: 2025-08-05 19:06:22.969157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd26d6cd4ea67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_specialists',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expertise_keywords', sa.JSON(), nullable=True),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slackmessage',
    sa.Column('slack_message_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('channel_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('subtype', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('thread_ts', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('parent_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('client_msg_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=True),
    sa.Column('reactions', sa.JSON(), nullable=True),
    sa.Column('edited', sa.JSON(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('reply_users_count', sa.Integer(), nullable=True),
    sa.Column('latest_reply', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=True),
    sa.Column('raw_event', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_ai_response', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slackmessage_slack_message_id'), 'slackmessage', ['slack_message_id'], unique=True)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_slackmessage_slack_message_id'), table_name='slackmessage')
    op.drop_table('slackmessage')
    op.drop_table('channel_specialists')
    # ### end Alembic commands ###
